plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'com.monowave.extractor'
version = '0.1.0'

android {
  namespace 'com.monowave.extractor'
  defaultConfig {
    minSdk 24
    versionCode 1
    versionName '0.1.0'
  }
  compileOptions { coreLibraryDesugaringEnabled true }
}

dependencies {
  implementation 'com.github.TeamNewPipe:NewPipeExtractor:v0.26.5'
  coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.1.5'
}
